name: test

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Testing dockerization of flask app
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies and script
        run: pip install -e .

      - name: Ensure config directory is clean
        run: krait reset

      - name: Create new krait flask project
        run: krait --skip-config create -n 'name' -e 'email' -p flask -s flask_project

      - name: Install & test newly created project
        run: |
          cd flask_project
          make install
          make test

      - name: Build docker container for flask app
        run: cd flask_project && make build

      - name: Run the container in the background
        run: cd flask_project && make run-d

      - name: Test the heartbeat route
        run: curl http://localhost/heartbeat

      - name: Teardown container
        if: ${{ always() }}
        run: cd flask_project && make stop
