name: pipeline

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.9'
  MAIN_GH_BRANCH: 'master'

jobs:
  test-ubuntu:
    uses: ./.github/workflows/test.yaml
    with:
      operating_system: ubuntu-latest

  test-macos:
    uses: ./.github/workflows/test.yaml
    with:
      operating_system: macos-latest

  test-windows:
    uses: ./.github/workflows/test.yaml
    with:
      operating_system: windows-latest


  version-check:
    needs: [test-ubuntu, test-macos, test-windows]
    uses: ./.github/workflows/version-check.yaml
    with:
      python-version: $PYTHON_VERSION

  code-analysis:
    needs: test-ubuntu
    uses: ./.github/workflows/codeql-analysis.yml

  build-package:
    needs: [version-check, code-analysis]
    if: ${{ needs.version-check.outputs.run_deploy == 'yes' && github.ref_name == $MAIN_GH_BRANCH }}
    uses: ./.github/workflows/build-package.yaml
    with:
      python-version: $PYTHON_VERSION

  build-changelog:
    needs: [version-check]
    if: ${{ needs.version-check.outputs.run_deploy == 'yes' && github.ref_name == $MAIN_GH_BRANCH }}
    uses: ./.github/workflows/build-changelog.yaml
    with:
      python-version: $PYTHON_VERSION

  release-github:
    needs: [build-changelog, build-package]
    uses: ./.github/workflows/release-github.yaml

  release-pypi:
    needs: [build-package]
    uses: ./.github/workflows/release-pypi.yaml
    with:
      python-version: $PYTHON_VERSION
