name: pipeline

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-python:
    runs-on: ubuntu-latest
    outputs:
      python-version: '3.9'
    steps:
      - name: Set needed elements as outputs
        run: echo "setting up needed elements"


  test-ubuntu:
    uses: ./.github/workflows/test.yaml
    with:
      operating_system: ubuntu-latest

  test-macos:
    uses: ./.github/workflows/test.yaml
    with:
      operating_system: macos-latest

  test-windows:
    uses: ./.github/workflows/test.yaml
    with:
      operating_system: windows-latest


  version-check:
    needs: [test-ubuntu, test-macos, test-windows, set-python]
    uses: ./.github/workflows/version-check.yaml
    if: github.ref_name == 'master'
    with:
      python-version: ${{ needs.set-python.outputs.python-version }}

  build-container:
    needs: [test-ubuntu, set-python]
    uses: ./.github/workflows/build-docker.yaml
    with:
      python-version: ${{ needs.set-python-outputs.python-version }}

  code-analysis:
    needs: test-ubuntu
    uses: ./.github/workflows/codeql-analysis.yml

  build-package:
    needs: [version-check, code-analysis, build-container]
    if: needs.version-check.outputs.run_deploy == 'yes'
    uses: ./.github/workflows/build-package.yaml
    with:
      python-version: ${{ needs.set-python-outputs.python-version }}

  build-changelog:
    needs: [version-check, build-container]
    if: needs.version-check.outputs.run_deploy == 'yes'
    uses: ./.github/workflows/build-changelog.yaml
    with:
      python-version: ${{ needs.set-python-outputs.python-version }}

  release-github:
    needs: [build-changelog, build-package]
    uses: ./.github/workflows/release-github.yaml

  release-pypi:
    needs: [build-package]
    uses: ./.github/workflows/release-pypi.yaml
    with:
      python-version: ${{ needs.set-python-outputs.python-version }}
