name: release_github

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      deploy-env:
        required: true
        type: string
      deploy-url:
        required: true
        type: string
      deploy-repo:
        required: true
        type: string


jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show python_version
        run: echo ${{ inputs.python_version }}

      - name: Show deploy-env
        run: echo ${{ inputs.deploy-env }}
  publish:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.deploy-env }}
      url: ${{ inputs.deploy-url }}
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install twine for upload
        run: pip install twine

      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: package-artifacts
          path: dist

      - name: Debug step
        run: echo '${{ inputs.deploy-repo }}'

      - name: Create release
        run: twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_REPOSITORY: ${{ inputs.deploy-repo }}
