name: test

on:
  workflow_call:
    inputs:
      operating_system:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        python: ['3.7', '3.8', '3.9', '3.10']
    name: Testing krait with python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Ensure latest pip
        run: pip install --upgrade pip

      - name: Install dependencies and script
        run: pip install -e .[tests]

      - name: Lint with flake8
        run: flake8
      - name: Run static type analyzer
        run: mypy

      - name: Test with pytest
        run: pytest tests/

      - name: Ensure config directory is clean
        run: krait reset

      - name: Create new krait click project
        run: krait --skip-config create -n '' -e '' -s project

      - name: Install & test newly created project
        run: |
          cd project
          pip install -e .[tests]
          project --help
          pytest

      - name: Clean up new project
        run: cd .. & rm -rf project

      - name: Create new krait lib project
        run: krait create -n '' -e '' -p library -s project

      - name: Install & test newly created project
        run: |
          cd project
          pip install -e .[tests]
          pytest

      - name: Clean up new project
        run: cd .. & rm -rf project
