name: version_check

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
    outputs:
      run-deploy:
        description: 'Whether or not the deployment should execute'
        value: ${{ jobs.version-check.outputs.run-deploy }}


jobs:
  version-check:
    runs-on: ubuntu-latest
    name: Verify version has been increased
    outputs:
      run-deploy: ${{ steps.verify.outputs.run_deploy }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install necessary package for scripts to run
        run: pip install packaging

      - name: Verify that the version has been increased
        id: verify
        run: echo "::set-output name=run_deploy::$(python scripts/version_verification.py $(python scripts/extract_version.py) $(cat VERSION))"

      - run: |
          echo "Version in VERSION file: $(cat VERSION)"
          echo "Last deployed version: $(python scripts/extract_version.py)"
          echo "Version increased: ${{ steps.verify.outputs.run_deploy }}"
